---

# We're currently only using Travis CI for automatic Forge deployment. No real
# test is run. This is specified here in order to override the default test.
script: /bin/true

deploy:
  provider: puppetforge
  user: reidmv
  password:
    secure: "jJHTOAwFPD6RlPMXP1TSorIvG9u94Wh6AFb6OKEF5ddeQ/RoioGY2PyWneyOUXnLhCDIuSAB/L1eDWNN5nPG47HcNqqEDOQcptzY43LgP+6UMo5rhlmr4eKgyq1c7L+bherlobxPhgVBkAK8ZeUJdYta2uFt5lhZNnWsoudG+q0="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
